# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: hello-world-a"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-a
  template:
    metadata:
      labels:
        app: hello-world-a
    spec:
      containers:
      - name: server
        image: asia-south1-docker.pkg.dev/mb-poc-352009/mb-devops/myimage
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
